-- supabase/seed/kenya_youth_markets.sql
-- 50 youth & millennial focused POLITICAL markets for Kenya/East Africa:
-- Gen-Z movement, 2027 youthquake, accountability, digital/meme politics,
-- broken-promise scorecards, county drama and regional youth waves.
-- 39 binary + 11 multiple_choice. Idempotent (ON CONFLICT slug).

DO $$
DECLARE cid uuid;
BEGIN
  SELECT id INTO cid FROM public.profiles
    ORDER BY (role='creator') DESC,(role='superadmin') DESC,(role='admin') DESC,created_at LIMIT 1;
  IF cid IS NULL THEN RAISE NOTICE 'No profile; skipping youth market seed.'; RETURN; END IF;

  INSERT INTO public.markets
    (slug,title,description,category,resolution_type,resolution_criteria,
     creator_id,status,opens_at,closes_at,resolves_at,
     yes_price,no_price,liquidity_pool_usd,initial_liquidity_usd,
     is_featured,is_trending,featured_order,tags,allowed_countries) VALUES
  ('ke-y-genz-protest-2026','Will Kenya see another nationwide Gen-Z-led protest in 2026?','Kenya''s Gen-Z reshaped politics in 2024. Will 2026 bring another nationwide, youth-led protest wave?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if coordinated youth-led protests occur in 5+ counties on the same cause in 2026 (major-media reported).',cid,'active',NOW(),'2026-12-31','2027-01-15',0.62,0.38,1500,1500,TRUE,TRUE,1,ARRAY['kenya','genz','protests','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-hashtag-number-one-2026','Will a political hashtag trend #1 in Kenya on X during a 2026 protest?','From #RejectFinanceBill to #RutoMustGo, Kenyan youth own the timeline. Will a political hashtag hit #1 in Kenya in 2026?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if a Kenyan political/protest hashtag reaches the #1 trending spot on X in Kenya during 2026 (screenshot/media evidence).',cid,'active',NOW(),'2026-12-31','2027-01-10',0.7,0.3,500,500,FALSE,TRUE,NULL,ARRAY['kenya','x','hashtag','genz'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-finance-bill-2027-protest','Will the Finance Bill 2027 trigger nationwide protests?','The Finance Bill is now a youth flashpoint every year. Will the 2027 edition spark nationwide protests?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if the Finance Bill 2027 provokes protests in 5+ counties before enactment (major-media reported).',cid,'active',NOW(),'2027-07-15','2027-07-31',0.6,0.4,500,500,FALSE,TRUE,NULL,ARRAY['kenya','finance-bill','protests','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-mobilization-platform-2026','Which platform will dominate Kenya''s youth political mobilization in 2026?','TikTok, X, WhatsApp — where will Kenya''s next movement actually organize?','social'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the platform most cited by major media as central to youth political mobilization in Kenya in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-20',0.5,0.5,900,900,FALSE,TRUE,NULL,ARRAY['kenya','genz','social-media'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-social-throttle-2026','Will the government throttle or restrict social media during a 2026 protest?','Internet slowdowns shadow protests across Africa. Will Kenya restrict social media during any 2026 protest?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if credible watchdogs (e.g., NetBlocks) confirm social-media restriction in Kenya during a 2026 protest.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.4,0.6,500,500,FALSE,TRUE,NULL,ARRAY['kenya','internet','censorship','protests'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-peoples-manifesto-2026','Will a Gen-Z "People''s Manifesto" be formally presented in 2026?','Youth movements are drafting demands. Will a Gen-Z "People''s Manifesto" be formally presented to Parliament/State in 2026?','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if a recognized youth movement formally presents a "People''s Manifesto" to Parliament or the Executive in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.45,0.55,500,500,FALSE,FALSE,NULL,ARRAY['kenya','genz','manifesto','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-occupy-parliament-2026','Will an #OccupyParliament-style action recur in 2026?','June 2024 saw youth breach Parliament. Will an "Occupy" action target a state institution again in 2026?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if an "Occupy"-branded youth action targets Parliament or a major state office in 2026 (major-media reported).',cid,'active',NOW(),'2026-12-31','2027-01-15',0.5,0.5,500,500,FALSE,TRUE,NULL,ARRAY['kenya','occupy','protests','genz'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-genz-preferred-2027','If only under-35s voted, who would win Kenya''s 2027 presidency?','Youth are Kenya''s largest voting bloc. Among under-35s in credible polling, who leads for 2027?','elections'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the candidate leading among 18–34 voters in the final credible pre-election poll before the 2027 vote.',cid,'active',NOW(),'2027-08-05','2027-08-20',0.5,0.5,1600,1600,TRUE,TRUE,2,ARRAY['kenya','genz','elections','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-youth-top-issue-2027','What is Kenyan youth voters'' #1 issue in 2027?','Jobs, cost of living, corruption — what will actually drive the youth vote?','politics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the issue ranked #1 by 18–34 voters in the final credible pre-election poll before the 2027 vote.',cid,'active',NOW(),'2027-08-01','2027-08-20',0.5,0.5,900,900,FALSE,TRUE,NULL,ARRAY['kenya','youth','issues','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-under35-governor-2027','Will a candidate under 35 win a governorship in 2027?','Kenya''s youngest leaders are rising. Will anyone under 35 win a county governorship in 2027?','elections'::market_category,'binary'::market_resolution_type,'Resolves YES if at least one person aged under 35 on election day is declared a county Governor-elect in 2027.',cid,'active',NOW(),'2027-08-10','2027-09-05',0.3,0.7,500,500,FALSE,FALSE,NULL,ARRAY['kenya','youth','governors','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-more-young-mps-2027','Will the number of MPs under 35 increase after 2027?','Will the 2027 election send more young faces to the National Assembly than the current House?','elections'::market_category,'binary'::market_resolution_type,'Resolves YES if the count of National Assembly members under 35 is higher after the 2027 election than before it.',cid,'active',NOW(),'2027-08-15','2027-09-15',0.45,0.55,500,500,FALSE,TRUE,NULL,ARRAY['kenya','youth','parliament','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-digital-first-candidate-wins-2027','Will a "digital-first" campaign win a major seat in 2027?','Some candidates skip rallies for reels. Will a primarily digital-first campaign win a governorship, Senate or big MP seat in 2027?','elections'::market_category,'binary'::market_resolution_type,'Resolves YES if a candidate widely profiled as running a "digital-first" campaign wins a Governor/Senator/major-constituency seat in 2027.',cid,'active',NOW(),'2027-08-10','2027-09-05',0.4,0.6,500,500,FALSE,TRUE,NULL,ARRAY['kenya','digital','campaign','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-record-youth-registration-2027','Will 18–34 voter registration hit a record for 2027?','The "silent majority" could roar. Will youth (18–34) voter registration set a record ahead of 2027?','elections'::market_category,'binary'::market_resolution_type,'Resolves YES if IEBC data shows record 18–34 voter registration numbers for the 2027 general election.',cid,'active',NOW(),'2027-06-30','2027-07-20',0.5,0.5,500,500,FALSE,TRUE,NULL,ARRAY['kenya','youth','iebc','registration'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-spoilt-protest-vote-2027','Will "reject them all" sentiment exceed 5% in a 2027 youth poll?','Disillusionment is real. Will a credible 2027 youth poll show >5% picking "none of the above"/boycott?','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if a credible pre-2027 poll reports >5% of 18–34 respondents choosing "none of the above" or boycott.',cid,'active',NOW(),'2027-07-31','2027-08-15',0.45,0.55,500,500,FALSE,FALSE,NULL,ARRAY['kenya','youth','apathy','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-defines-2027','What will define Kenya''s 2027 election?','Youthquake, apathy, or business as usual — what will the story of 2027 be?','elections'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the narrative judged by major-media consensus to have defined the 2027 election.',cid,'active',NOW(),'2027-08-20','2027-09-10',0.5,0.5,800,800,FALSE,TRUE,NULL,ARRAY['kenya','elections','2027','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-most-broken-promise-2027','Which government promise will youth judge most broken by 2027?','Housing, Hustler Fund, jobs — which pledge will Kenyans feel was most broken?','politics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the promise ranked "most broken" by 18–34 respondents in a credible 2027 poll.',cid,'active',NOW(),'2027-06-30','2027-07-20',0.5,0.5,800,800,FALSE,TRUE,NULL,ARRAY['kenya','promises','accountability','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-mp-recall-2026','Will any sitting MP be successfully recalled in 2026?','Youth keep demanding recall powers. Will any sitting MP actually be recalled in 2026?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if any sitting Member of Parliament is officially recalled from office during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.12,0.88,500,500,FALSE,FALSE,NULL,ARRAY['kenya','recall','accountability'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-viral-corruption-expose-2026','Will a viral exposé force a Kenyan official to resign/step aside in 2026?','Citizen journalism keeps landing hits. Will a viral online exposé force an official to resign or step aside in 2026?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if a public official in Kenya resigns/steps aside in 2026 directly following a viral online exposé (major-media reported).',cid,'active',NOW(),'2026-12-31','2027-01-20',0.4,0.6,500,500,FALSE,TRUE,NULL,ARRAY['kenya','corruption','accountability'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-housing-levy-still-2026','Will the Housing Levy still be in force at end of 2026?','The Housing Levy is a lightning rod for young workers. Will it still be deducted at end-2026?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if the mandatory Affordable Housing Levy remains legally in force on 31 December 2026.',cid,'active',NOW(),'2026-12-31','2027-01-10',0.75,0.25,500,500,FALSE,TRUE,NULL,ARRAY['kenya','housing-levy','tax','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-hustler-fund-default-2026','Will the Hustler Fund default rate be reported above 60% in 2026?','The Hustler Fund was a flagship youth pledge. Will official 2026 figures show a default rate above 60%?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if official/Treasury figures report a Hustler Fund default (non-performing) rate above 60% during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,500,500,FALSE,FALSE,NULL,ARRAY['kenya','hustler-fund','youth','economics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-million-jobs-500k-2026','Will the government report 500k+ new jobs toward its pledge by end 2026?','The "million jobs" pledge is a youth scorecard. Will an official update claim 500k+ new jobs by end-2026?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if an official government report claims 500,000+ new formal jobs created toward the pledge by 31 December 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.35,0.65,500,500,FALSE,FALSE,NULL,ARRAY['kenya','jobs','youth','economics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-deepfake-viral-2026','Will an AI political deepfake go viral in Kenya during 2026?','AI is entering the campaign. Will an AI-generated deepfake of a Kenyan politician go viral in 2026?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if an AI-generated deepfake of a Kenyan political figure goes viral and is fact-checked by major media in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.55,0.45,500,500,FALSE,TRUE,NULL,ARRAY['kenya','ai','deepfake','politics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-protest-anthem-2026','Will a song or meme become the anthem of a 2026 Kenyan protest?','From "Anguka Nayo" to protest chants, culture leads. Will a song/meme become a 2026 protest anthem?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if a specific song or meme is widely credited by major media as the anthem of a 2026 Kenyan protest.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.6,0.4,500,500,FALSE,TRUE,NULL,ARRAY['kenya','music','protests','culture'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-new-political-nickname-2026','Will a new viral political nickname catch on in 2026?','Kenyans nickname power ("Zakayo", "Deputy Jesus"). Will a fresh viral political nickname dominate the timeline in 2026?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if a new nickname for a Kenyan political figure becomes widely used and media-documented in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.65,0.35,500,500,FALSE,FALSE,NULL,ARRAY['kenya','culture','memes','politics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-most-influential-digital-voice-2026','Which type of digital voice will most shape Kenyan politics in 2026?','Who really moves opinion online — creators, journalists, or anonymous accounts?','social'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the category most cited by major-media analyses as shaping Kenyan political discourse online in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,700,700,FALSE,FALSE,NULL,ARRAY['kenya','digital','influence','2026'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-celebrity-2027-bid','Will a Kenyan musician or celebrity declare a 2027 political bid?','Celebrity politics is rising. Will a well-known Kenyan artist/celebrity declare a 2027 elective bid?','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if a nationally known Kenyan musician/celebrity publicly declares candidacy for a 2027 elective seat.',cid,'active',NOW(),'2027-05-31','2027-06-15',0.55,0.45,500,500,FALSE,TRUE,NULL,ARRAY['kenya','celebrity','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-creator-wins-seat-2027','Will a content creator/YouTuber win an elective seat in 2027?','The creator economy meets the ballot. Will a Kenyan content creator/YouTuber win an elective seat in 2027?','elections'::market_category,'binary'::market_resolution_type,'Resolves YES if a person primarily known as a content creator/YouTuber wins any elective seat in the 2027 election.',cid,'active',NOW(),'2027-08-10','2027-09-05',0.28,0.72,500,500,FALSE,FALSE,NULL,ARRAY['kenya','creator','youth','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-genz-party-registered-2027','Will a Gen-Z coalition or party register with the ORPP before 2027?','Leaderless in 2024 — organized by 2027? Will a self-described Gen-Z party/coalition register with the ORPP before the election?','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if a party/coalition branded as Gen-Z/youth-led is officially registered by the ORPP before the 2027 election.',cid,'active',NOW(),'2027-05-31','2027-06-20',0.35,0.65,500,500,FALSE,TRUE,NULL,ARRAY['kenya','genz','party','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-slogan-2027','Which slogan will dominate Kenya''s 2027 campaign?','"Wantam", "Reject", or something fresh — which chant owns 2027?','politics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the slogan most cited by major media as dominating the 2027 campaign.',cid,'active',NOW(),'2027-08-01','2027-08-20',0.5,0.5,800,800,FALSE,TRUE,NULL,ARRAY['kenya','slogan','2027','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-e-registration-diaspora-2027','Will the IEBC roll out online voter registration for youth/diaspora by 2027?','Digital natives want digital democracy. Will the IEBC enable online/e-registration for the 2027 cycle?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if the IEBC officially launches online/e-voter registration usable for the 2027 election.',cid,'active',NOW(),'2027-05-31','2027-06-20',0.35,0.65,500,500,FALSE,FALSE,NULL,ARRAY['kenya','iebc','digital','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-election-day-shutdown-2027','Will Kenya''s internet be shut down on any 2027 election-related day?','A red line for young voters. Will there be a confirmed internet shutdown on any 2027 election-related day?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if watchdogs (e.g., NetBlocks) confirm a nationwide internet shutdown in Kenya on any 2027 election-related day.',cid,'active',NOW(),'2027-08-20','2027-09-05',0.15,0.85,500,500,FALSE,TRUE,NULL,ARRAY['kenya','internet','elections','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-youth-litigation-blocks-policy-2026','Will youth-led litigation block a major government policy in 2026?','The courts are a youth battleground. Will youth-led litigation block or suspend a major policy in 2026?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if a court blocks/suspends a major government policy in 2026 in a case led by youth/civil-society petitioners.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,500,500,FALSE,FALSE,NULL,ARRAY['kenya','courts','youth','accountability'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-digital-tax-backlash-2026','Will a new digital/social-media tax spark youth backlash in 2026?','Tax the timeline? Will a new digital or social-media-related tax proposal spark organized youth backlash in 2026?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if a new digital/social-media tax proposal triggers organized youth backlash (major-media reported) in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-20',0.45,0.55,500,500,FALSE,FALSE,NULL,ARRAY['kenya','tax','digital','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-under30-cabinet-2026','Will a Kenyan under 30 be appointed to a CS/PS role in 2026?','Representation at the top? Will anyone under 30 be appointed a Cabinet Secretary or Principal Secretary in 2026?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if a person under 30 is appointed CS or PS in Kenya during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.2,0.8,500,500,FALSE,FALSE,NULL,ARRAY['kenya','youth','cabinet'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-ruto-youth-approval-40-2026','Will Ruto''s approval among under-35s top 40% in any 2026 poll?','Can the President win back the youth? Will his approval among under-35s exceed 40% in any credible 2026 poll?','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if a credible 2026 poll reports President Ruto''s approval among 18–34 respondents above 40%.',cid,'active',NOW(),'2026-12-31','2027-01-20',0.4,0.6,500,500,FALSE,TRUE,NULL,ARRAY['kenya','ruto','youth','approval'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-gachagua-youth-face-2026','Will Gachagua become the leading opposition "youth" rallying figure by end 2026?','An unlikely youth ally? Will Gachagua be widely cast as the leading opposition figure rallying youth by end-2026?','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if major-media consensus by end-2026 casts Rigathi Gachagua as the leading opposition figure rallying youth.',cid,'active',NOW(),'2026-12-31','2027-01-20',0.4,0.6,500,500,FALSE,FALSE,NULL,ARRAY['kenya','gachagua','opposition','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-youth-trust-most-2027','Who will Kenyan youth trust most to defend their interests in 2027?','Politicians, activists, the church, or creators — who earns youth trust?','politics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the group Kenyan youth trust most to defend their interests in a credible 2027 poll.',cid,'active',NOW(),'2027-06-30','2027-07-20',0.5,0.5,800,800,FALSE,TRUE,NULL,ARRAY['kenya','youth','trust','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-ea-candidacy-age-2027','Will any East African country lower a candidacy age limit by 2027?','Young leaders, old rules. Will any EAC country lower an elective candidacy age limit before 2027?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if any East African country legally lowers a candidacy age limit for elective office before the end of 2027.',cid,'active',NOW(),'2027-12-31','2028-01-31',0.2,0.8,500,500,FALSE,FALSE,NULL,ARRAY['east-africa','youth','governance'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-eac-youth-mobility-2026','Will the EAC ease youth work/mobility rules in 2026?','One region, one youth market? Will the EAC adopt measures easing youth work/mobility across borders in 2026?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if the EAC formally adopts a measure easing youth work/mobility across member states in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.3,0.7,500,500,FALSE,FALSE,NULL,ARRAY['east-africa','eac','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-ea-youth-protest-spillover-2026','Will a youth protest movement spread across 2+ EA countries in 2026?','Movements cross borders. Will a youth-led protest wave visibly spread across 2+ East African countries in 2026?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if major media report a youth-led protest movement spreading across 2+ East African countries in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-20',0.35,0.65,500,500,FALSE,TRUE,NULL,ARRAY['east-africa','youth','protests'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-governor-impeached-2026','Will any Kenyan county governor be impeached in 2026?','Devolution drama. Will any sitting county governor be impeached during 2026?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if any sitting county governor is impeached (assembly + senate outcome) during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.4,0.6,500,500,FALSE,FALSE,NULL,ARRAY['kenya','governors','impeachment'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-county-accountability-push-2026','Which county will see the biggest youth accountability push in 2026?','Where will young people most fiercely demand accountability in 2026?','social'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the county most cited by major media for youth-led accountability action in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,600,600,FALSE,FALSE,NULL,ARRAY['kenya','counties','youth','2026'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-nairobi-youth-unemployment-down-2026','Will Nairobi youth unemployment officially fall in 2026?','The number that decides elections. Will official data show Nairobi youth unemployment falling in 2026?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if KNBS/official data show a year-on-year fall in Nairobi youth (18–34) unemployment for 2026.',cid,'active',NOW(),'2027-02-28','2027-03-31',0.35,0.65,500,500,FALSE,FALSE,NULL,ARRAY['kenya','nairobi','jobs','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-harambee-10m-cause-2026','Will an online fundraiser for a civic cause top KES 10M in 2026?','Digital harambees fund movements. Will an online fundraiser for a protest/civic cause exceed KES 10M in 2026?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if a verifiable online fundraiser for a Kenyan civic/protest cause exceeds KES 10,000,000 in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,500,500,FALSE,TRUE,NULL,ARRAY['kenya','crowdfunding','civic','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-campus-leader-national-2027','Will a campus/student leader become a national 2027 candidate?','From SONU to the ballot. Will a current/recent university student leader run as a notable 2027 candidate?','elections'::market_category,'binary'::market_resolution_type,'Resolves YES if a current/recent university student leader runs as a widely covered candidate in the 2027 election.',cid,'active',NOW(),'2027-06-30','2027-07-20',0.4,0.6,500,500,FALSE,FALSE,NULL,ARRAY['kenya','campus','youth','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-cost-of-living-top-concern-2026','Will "cost of living" stay Kenyan youths'' #1 concern through 2026?','The unrelenting issue. Will "cost of living" remain the top-cited concern among Kenyan youth across 2026 polls?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if "cost of living" is the most-cited concern among 18–34 Kenyans in the majority of credible 2026 polls.',cid,'active',NOW(),'2026-12-31','2027-01-20',0.7,0.3,500,500,FALSE,TRUE,NULL,ARRAY['kenya','cost-of-living','youth'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-youth-news-source-2027','By 2027, where will Kenyan youth get most of their political news?','TV is fading, feeds are winning. Where will youth actually get political news by 2027?','social'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the source most-cited by 18–34 Kenyans for political news in a credible 2027 media survey.',cid,'active',NOW(),'2027-06-30','2027-07-31',0.5,0.5,700,700,FALSE,TRUE,NULL,ARRAY['kenya','media','youth','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-boda-vote-courted-2027','Will boda-boda youth be openly courted as a decisive 2027 bloc?','Millions of riders, millions of votes. Will boda-boda youth be openly courted as a decisive 2027 voting bloc?','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if major parties/candidates publicly launch dedicated boda-boda youth outreach as a decisive 2027 bloc.',cid,'active',NOW(),'2027-07-31','2027-08-15',0.7,0.3,500,500,FALSE,FALSE,NULL,ARRAY['kenya','boda-boda','youth','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-genz-memorial-2026','Will June 25 be marked as a national Gen-Z remembrance day in 2026?','A date seared into memory. Will 25 June 2026 see organized nationwide Gen-Z remembrance events?','social'::market_category,'binary'::market_resolution_type,'Resolves YES if organized Gen-Z remembrance events occur in 5+ counties around 25 June 2026 (major-media reported).',cid,'active',NOW(),'2026-07-15','2026-07-31',0.75,0.25,500,500,FALSE,TRUE,NULL,ARRAY['kenya','genz','memorial','2026'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-y-first-youth-demand-met-2026','Which major youth demand will the government act on first in 2026?','Youth have a list. Which demand will the government visibly move on first in 2026?','politics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the first demand the government visibly acts on in 2026 (major-media reported); "None" if none by year-end.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,700,700,FALSE,TRUE,NULL,ARRAY['kenya','youth','demands','2026'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI'])
  ON CONFLICT (slug) DO NOTHING;
END $$;

-- Multiple-choice options (idempotent per market).
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'TikTok',0.34,0 FROM public.markets m WHERE slug='ke-y-mobilization-platform-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'X (Twitter)',0.33,1 FROM public.markets m WHERE slug='ke-y-mobilization-platform-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'WhatsApp',0.16,2 FROM public.markets m WHERE slug='ke-y-mobilization-platform-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Instagram',0.1,3 FROM public.markets m WHERE slug='ke-y-mobilization-platform-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Facebook',0.07,4 FROM public.markets m WHERE slug='ke-y-mobilization-platform-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'William Ruto',0.24,0 FROM public.markets m WHERE slug='ke-y-genz-preferred-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Rigathi Gachagua',0.22,1 FROM public.markets m WHERE slug='ke-y-genz-preferred-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Kalonzo Musyoka',0.16,2 FROM public.markets m WHERE slug='ke-y-genz-preferred-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Fred Matiang''i',0.16,3 FROM public.markets m WHERE slug='ke-y-genz-preferred-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'None of the above',0.14,4 FROM public.markets m WHERE slug='ke-y-genz-preferred-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Someone else',0.08,5 FROM public.markets m WHERE slug='ke-y-genz-preferred-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=5);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Jobs / unemployment',0.34,0 FROM public.markets m WHERE slug='ke-y-youth-top-issue-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Cost of living',0.3,1 FROM public.markets m WHERE slug='ke-y-youth-top-issue-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Corruption',0.18,2 FROM public.markets m WHERE slug='ke-y-youth-top-issue-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Education / HELB funding',0.1,3 FROM public.markets m WHERE slug='ke-y-youth-top-issue-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Police brutality',0.08,4 FROM public.markets m WHERE slug='ke-y-youth-top-issue-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'A youthquake (record youth turnout)',0.3,0 FROM public.markets m WHERE slug='ke-y-defines-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Tribal alignments as usual',0.3,1 FROM public.markets m WHERE slug='ke-y-defines-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Voter apathy',0.24,2 FROM public.markets m WHERE slug='ke-y-defines-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Protest / boycott',0.1,3 FROM public.markets m WHERE slug='ke-y-defines-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Something entirely new',0.06,4 FROM public.markets m WHERE slug='ke-y-defines-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Job creation',0.3,0 FROM public.markets m WHERE slug='ke-y-most-broken-promise-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Lower cost of living',0.28,1 FROM public.markets m WHERE slug='ke-y-most-broken-promise-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Affordable Housing',0.18,2 FROM public.markets m WHERE slug='ke-y-most-broken-promise-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Hustler Fund',0.14,3 FROM public.markets m WHERE slug='ke-y-most-broken-promise-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Cheaper fertilizer/farming',0.1,4 FROM public.markets m WHERE slug='ke-y-most-broken-promise-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Content creators / influencers',0.3,0 FROM public.markets m WHERE slug='ke-y-most-influential-digital-voice-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Citizen journalists',0.26,1 FROM public.markets m WHERE slug='ke-y-most-influential-digital-voice-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Anonymous whistleblower accounts',0.2,2 FROM public.markets m WHERE slug='ke-y-most-influential-digital-voice-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Comedians / satirists',0.14,3 FROM public.markets m WHERE slug='ke-y-most-influential-digital-voice-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Student leaders',0.1,4 FROM public.markets m WHERE slug='ke-y-most-influential-digital-voice-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'"Wantam" (one term)',0.34,0 FROM public.markets m WHERE slug='ke-y-slogan-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'"We are watching"',0.22,1 FROM public.markets m WHERE slug='ke-y-slogan-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'"Reject / Occupy"',0.2,2 FROM public.markets m WHERE slug='ke-y-slogan-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'"Ruto for 2027"',0.16,3 FROM public.markets m WHERE slug='ke-y-slogan-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Something fresh',0.08,4 FROM public.markets m WHERE slug='ke-y-slogan-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Civil society / activists',0.3,0 FROM public.markets m WHERE slug='ke-y-youth-trust-most-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Content creators / influencers',0.24,1 FROM public.markets m WHERE slug='ke-y-youth-trust-most-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Opposition politicians',0.2,2 FROM public.markets m WHERE slug='ke-y-youth-trust-most-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'The church',0.14,3 FROM public.markets m WHERE slug='ke-y-youth-trust-most-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'No one',0.12,4 FROM public.markets m WHERE slug='ke-y-youth-trust-most-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Nairobi',0.4,0 FROM public.markets m WHERE slug='ke-y-county-accountability-push-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Mombasa',0.16,1 FROM public.markets m WHERE slug='ke-y-county-accountability-push-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Kisumu',0.16,2 FROM public.markets m WHERE slug='ke-y-county-accountability-push-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Nakuru',0.14,3 FROM public.markets m WHERE slug='ke-y-county-accountability-push-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Uasin Gishu (Eldoret)',0.14,4 FROM public.markets m WHERE slug='ke-y-county-accountability-push-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'TikTok',0.3,0 FROM public.markets m WHERE slug='ke-y-youth-news-source-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'X (Twitter)',0.24,1 FROM public.markets m WHERE slug='ke-y-youth-news-source-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'WhatsApp groups',0.2,2 FROM public.markets m WHERE slug='ke-y-youth-news-source-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'YouTube',0.14,3 FROM public.markets m WHERE slug='ke-y-youth-news-source-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Mainstream TV',0.12,4 FROM public.markets m WHERE slug='ke-y-youth-news-source-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'University / HELB funding fix',0.28,0 FROM public.markets m WHERE slug='ke-y-first-youth-demand-met-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Youth jobs stimulus',0.24,1 FROM public.markets m WHERE slug='ke-y-first-youth-demand-met-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Housing Levy relief',0.18,2 FROM public.markets m WHERE slug='ke-y-first-youth-demand-met-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Police accountability reforms',0.16,3 FROM public.markets m WHERE slug='ke-y-first-youth-demand-met-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'None of these',0.14,4 FROM public.markets m WHERE slug='ke-y-first-youth-demand-met-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
