-- supabase/seed/kenya_markets.sql
-- 50 Kenya-focused prediction markets (39 binary + 11 multiple_choice),
-- across politics, elections, economics, business, sports, crypto, tech,
-- weather, health, social & entertainment. Idempotent (ON CONFLICT slug).
-- Multi-choice markets seed their market_options with normalized odds.

DO $$
DECLARE cid uuid;
BEGIN
  SELECT id INTO cid FROM public.profiles
    ORDER BY (role='creator') DESC, (role='superadmin') DESC, (role='admin') DESC, created_at LIMIT 1;
  IF cid IS NULL THEN RAISE NOTICE 'No profile found; skipping Kenya market seed.'; RETURN; END IF;

  INSERT INTO public.markets
    (slug,title,description,category,resolution_type,resolution_criteria,
     creator_id,status,opens_at,closes_at,resolves_at,
     yes_price,no_price,liquidity_pool_usd,initial_liquidity_usd,
     is_featured,is_trending,featured_order,tags,allowed_countries) VALUES
  ('ke-2027-president','Who will win Kenya''s 2027 presidential election?','Kenya''s next general election is due in August 2027. This market resolves to the candidate declared president-elect by the IEBC (after any court petitions).','elections'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the candidate the IEBC/courts declare winner of the 2027 presidential election.',cid,'active',NOW(),'2027-08-10','2027-09-15',0.5,0.5,2000,2000,TRUE,TRUE,1,ARRAY['kenya','politics','elections','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-ruto-reelection-2027','Will William Ruto win re-election in 2027?','President William Ruto is expected to seek a second term in the August 2027 general election.','elections'::market_category,'binary'::market_resolution_type,'Resolves YES if William Ruto is declared president-elect for a second term after the 2027 election.',cid,'active',NOW(),'2027-08-10','2027-09-15',0.46,0.54,1500,1500,TRUE,TRUE,2,ARRAY['kenya','ruto','elections','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-opposition-flagbearer-2027','Who will be the United Opposition''s 2027 presidential flag-bearer?','The United Opposition says it will name a single candidate after the IEBC deadline. This market tracks who that flag-bearer will be.','politics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the person unveiled as the United Opposition''s single presidential candidate for 2027.',cid,'active',NOW(),'2027-05-20','2027-06-10',0.5,0.5,1200,1200,FALSE,TRUE,NULL,ARRAY['kenya','opposition','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-opposition-names-candidate-before-may2027','Will the opposition name its 2027 candidate before 15 May 2027?','Gachagua has said the United Opposition will only name its candidate after the IEBC deadline of 15 May 2027 to avoid "state persecution".','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if the United Opposition publicly unveils a single presidential candidate on or before 15 May 2027.',cid,'active',NOW(),'2027-05-15','2027-05-20',0.22,0.78,400,400,FALSE,TRUE,NULL,ARRAY['kenya','opposition','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-ruto-running-mate-2027','Who will be William Ruto''s running mate in 2027?','Speculation surrounds Ruto''s 2027 deputy-president pick, with several names in the mix.','politics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the person named as Ruto''s official running mate for the 2027 election.',cid,'active',NOW(),'2027-06-30','2027-07-15',0.5,0.5,900,900,FALSE,FALSE,NULL,ARRAY['kenya','ruto','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-nairobi-governor-2027','Who will win the 2027 Nairobi gubernatorial race?','Nairobi County elects its governor in August 2027.','elections'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the candidate declared Nairobi Governor-elect by the IEBC in 2027.',cid,'active',NOW(),'2027-08-10','2027-09-01',0.5,0.5,700,700,FALSE,FALSE,NULL,ARRAY['kenya','nairobi','elections','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-kindiki-running-mate-2027','Will Kithure Kindiki be Ruto''s running mate in 2027?','Kindiki is the current frontrunner to retain the deputy-president slot on Ruto''s ticket.','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if Kithure Kindiki is named Ruto''s official running mate for 2027.',cid,'active',NOW(),'2027-06-30','2027-07-15',0.55,0.45,400,400,FALSE,FALSE,NULL,ARRAY['kenya','kindiki','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-turnout-above-65-2027','Will voter turnout exceed 65% in Kenya''s 2027 general election?','Kenya''s 2022 general election recorded roughly 65% turnout. Will 2027 beat it?','elections'::market_category,'binary'::market_resolution_type,'Resolves YES if IEBC official presidential turnout for the 2027 general election exceeds 65%.',cid,'active',NOW(),'2027-08-10','2027-08-25',0.48,0.52,400,400,FALSE,FALSE,NULL,ARRAY['kenya','elections','turnout','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-iebc-chair-before-2027','Will a new IEBC chairperson be gazetted before Dec 2026?','A fully reconstituted IEBC is critical for 2027 election preparations.','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if a substantive IEBC chairperson is officially gazetted on or before 31 December 2026.',cid,'active',NOW(),'2026-12-31','2027-01-10',0.6,0.4,400,400,FALSE,TRUE,NULL,ARRAY['kenya','iebc','governance'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-referendum-before-2027','Will Kenya hold a national referendum before the 2027 election?','Talk of constitutional amendments recurs. Will a national referendum actually take place before August 2027?','governance'::market_category,'binary'::market_resolution_type,'Resolves YES if a national referendum is held in Kenya at any time before the 2027 general election.',cid,'active',NOW(),'2027-08-01','2027-08-15',0.18,0.82,400,400,FALSE,FALSE,NULL,ARRAY['kenya','referendum','governance'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-most-assembly-seats-2027','Which coalition will win the most National Assembly seats in 2027?','The composition of the next National Assembly is a key 2027 storyline.','elections'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the coalition that wins the most elected National Assembly seats in the 2027 election.',cid,'active',NOW(),'2027-08-10','2027-09-01',0.5,0.5,700,700,FALSE,FALSE,NULL,ARRAY['kenya','parliament','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-kes-stronger-130-eoy2026','Will the Kenyan shilling be stronger than 130 KES/USD at end of 2026?','The shilling has been relatively stable around the high-120s to low-130s. Will it hold below 130 at year-end?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if the CBK official USD/KES mean rate on the last trading day of 2026 is below 130.00.',cid,'active',NOW(),'2026-12-31','2027-01-05',0.55,0.45,400,400,FALSE,TRUE,NULL,ARRAY['kenya','shilling','forex','cbk'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-cbk-rate-dec2026','What will the CBK benchmark rate be after the final 2026 MPC meeting?','The Central Bank of Kenya has been easing policy. This market bands the Central Bank Rate after the last MPC of 2026.','economics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the band containing the CBK Central Bank Rate announced at the final 2026 Monetary Policy Committee meeting.',cid,'active',NOW(),'2026-12-15','2026-12-20',0.5,0.5,800,800,FALSE,FALSE,NULL,ARRAY['kenya','cbk','interest-rates','economics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-inflation-below-5-dec2026','Will Kenya''s annual inflation be below 5% in December 2026?','CBK targets inflation at 5% (±2.5%). This tracks the KNBS December 2026 year-on-year CPI print.','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if KNBS official December 2026 year-on-year inflation is below 5.0%.',cid,'active',NOW(),'2026-12-28','2027-01-15',0.62,0.38,400,400,FALSE,FALSE,NULL,ARRAY['kenya','inflation','knbs','economics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-imf-programme-2026','Will Kenya agree a new IMF programme before end of 2026?','A new IMF arrangement is anticipated to anchor fiscal credibility ahead of 2027.','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if the IMF Board approves a new financing programme for Kenya on or before 31 December 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.5,0.5,400,400,FALSE,FALSE,NULL,ARRAY['kenya','imf','economics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-nse20-above-2200-eoy2026','Will the NSE 20 Share Index close above 2,200 at end of 2026?','The Nairobi Securities Exchange benchmark has rebounded. Will it end 2026 above 2,200?','business'::market_category,'binary'::market_resolution_type,'Resolves YES if the NSE 20 Share Index official close on the last trading day of 2026 is above 2,200.',cid,'active',NOW(),'2026-12-31','2027-01-05',0.45,0.55,400,400,FALSE,FALSE,NULL,ARRAY['kenya','nse','stocks','business'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-safaricom-above-30-eoy2026','Will Safaricom close above KES 30 on the NSE by end of 2026?','Safaricom is the NSE''s largest counter. Will its share price finish 2026 above KES 30?','business'::market_category,'binary'::market_resolution_type,'Resolves YES if Safaricom PLC (SCOM) official closing price on the last NSE trading day of 2026 is above KES 30.00.',cid,'active',NOW(),'2026-12-31','2027-01-05',0.4,0.6,400,400,FALSE,TRUE,NULL,ARRAY['kenya','safaricom','nse','business'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-eurobond-2026','Will Kenya issue a new Eurobond in 2026?','Kenya has tapped international markets to manage debt. Will it issue a new Eurobond during 2026?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if the Kenyan government prices a new Eurobond issuance at any point in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-10',0.55,0.45,400,400,FALSE,FALSE,NULL,ARRAY['kenya','eurobond','debt','economics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-top-fdi-sector-2026','Which sector will attract the most FDI into Kenya in 2026?','Foreign direct investment is spread across Kenya''s fast-growing sectors.','business'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the sector reported as attracting the largest FDI inflows into Kenya for 2026 (official/UNCTAD/CBK data).',cid,'active',NOW(),'2027-01-31','2027-03-31',0.5,0.5,600,600,FALSE,FALSE,NULL,ARRAY['kenya','fdi','business'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-petrol-above-200-2026','Will Nairobi super-petrol exceed KES 200/litre at any point in 2026?','EPRA sets monthly fuel prices. Will Nairobi super-petrol cross KES 200 per litre during 2026?','economics'::market_category,'binary'::market_resolution_type,'Resolves YES if the EPRA-gazetted Nairobi super-petrol pump price is KES 200.00/litre or higher in any month of 2026.',cid,'active',NOW(),'2026-12-31','2027-01-10',0.5,0.5,400,400,FALSE,FALSE,NULL,ARRAY['kenya','fuel','epra','economics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-mpesa-record-2026','Will M-Pesa post a record annual transaction value in 2026?','M-Pesa volumes keep climbing. Will Safaricom report an all-time-high annual M-Pesa transaction value for 2026?','business'::market_category,'binary'::market_resolution_type,'Resolves YES if Safaricom''s official reporting shows record annual M-Pesa total transaction value for the 2026 period.',cid,'active',NOW(),'2027-05-31','2027-06-15',0.7,0.3,400,400,FALSE,FALSE,NULL,ARRAY['kenya','mpesa','safaricom','fintech'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-afcon-stadia-pass-2027','Will Kenya''s AFCON 2027 stadiums pass CAF''s final inspection?','Kenya co-hosts AFCON 2027 with Uganda and Tanzania (19 June–18 July 2027) and must pass CAF venue inspections.','sports'::market_category,'binary'::market_resolution_type,'Resolves YES if CAF officially approves Kenya''s designated AFCON 2027 stadiums in its final pre-tournament inspection.',cid,'active',NOW(),'2027-05-31','2027-06-10',0.72,0.28,1200,1200,TRUE,TRUE,3,ARRAY['kenya','afcon','2027','football'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-talanta-complete-2026','Will Talanta Stadium be officially handed over by 31 Dec 2026?','Talanta (Raila Odinga International) Stadium is a flagship AFCON 2027 venue targeted for completion by end-2026.','sports'::market_category,'binary'::market_resolution_type,'Resolves YES if Talanta Stadium is officially completed and handed over on or before 31 December 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.6,0.4,400,400,FALSE,TRUE,NULL,ARRAY['kenya','talanta','afcon','stadium'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-harambee-past-group-2027','Will Harambee Stars advance past the AFCON 2027 group stage?','Kenya qualifies automatically as co-hosts. Can Benni McCarthy''s side reach the knockout rounds on home soil?','sports'::market_category,'binary'::market_resolution_type,'Resolves YES if Kenya (Harambee Stars) advances to the Round of 16 or beyond at AFCON 2027.',cid,'active',NOW(),'2027-07-05','2027-07-10',0.4,0.6,1000,1000,TRUE,TRUE,4,ARRAY['kenya','harambee-stars','afcon','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-harambee-run-2027','How far will Harambee Stars go at AFCON 2027?','Kenya''s best-ever AFCON showing is a group-stage exit. As co-hosts, how deep will they run in 2027?','sports'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the furthest stage Harambee Stars reach at AFCON 2027.',cid,'active',NOW(),'2027-07-18','2027-07-22',0.5,0.5,900,900,FALSE,TRUE,NULL,ARRAY['kenya','harambee-stars','afcon','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-kenyan-berlin-men-2026','Will a Kenyan win the men''s 2026 Berlin Marathon?','Kenyans have dominated Berlin. Will a Kenyan take the men''s title in September 2026?','sports'::market_category,'binary'::market_resolution_type,'Resolves YES if an athlete representing Kenya wins the elite men''s race at the 2026 Berlin Marathon.',cid,'active',NOW(),'2026-09-27','2026-09-29',0.7,0.3,400,400,FALSE,FALSE,NULL,ARRAY['kenya','marathon','athletics','berlin'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-kipyegon-wr-2026','Will Faith Kipyegon set a world record in 2026?','Faith Kipyegon has repeatedly rewritten middle-distance history. Will she set another ratified world record in 2026?','sports'::market_category,'binary'::market_resolution_type,'Resolves YES if World Athletics ratifies a new world record set by Faith Kipyegon during 2026.',cid,'active',NOW(),'2026-12-31','2027-02-28',0.45,0.55,400,400,FALSE,TRUE,NULL,ARRAY['kenya','kipyegon','athletics'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-ea-athletics-top-2026','Which East African nation will top the 2026 World Athletics medal table (among EA)?','Kenya, Ethiopia and Uganda annually contest East African athletics supremacy.','sports'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the East African country with the most medals at the 2026 World Athletics Championships/season events.',cid,'active',NOW(),'2026-09-30','2026-10-15',0.5,0.5,600,600,FALSE,FALSE,NULL,ARRAY['kenya','athletics','2026'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-mccarthy-coach-afcon','Will Benni McCarthy still be Harambee Stars head coach at AFCON 2027 kickoff?','Benni McCarthy leads Harambee Stars into their home AFCON. Will he still be in charge at kickoff?','sports'::market_category,'binary'::market_resolution_type,'Resolves YES if Benni McCarthy is the substantive Harambee Stars head coach on the opening day of AFCON 2027.',cid,'active',NOW(),'2027-06-18','2027-06-20',0.6,0.4,400,400,FALSE,FALSE,NULL,ARRAY['kenya','harambee-stars','afcon'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-knockout-at-kasarani-2027','Will Kasarani host an AFCON 2027 knockout match?','Moi International Sports Centre, Kasarani is a flagship Kenyan AFCON venue.','sports'::market_category,'binary'::market_resolution_type,'Resolves YES if at least one AFCON 2027 knockout-stage match is officially scheduled and played at Kasarani.',cid,'active',NOW(),'2027-06-30','2027-07-20',0.65,0.35,400,400,FALSE,FALSE,NULL,ARRAY['kenya','kasarani','afcon'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-btc-150k-2026','Will Bitcoin trade above $150,000 at any point in 2026?','Bitcoin''s 2025 run has traders eyeing new highs. Will BTC/USD print above $150k during 2026?','crypto'::market_category,'binary'::market_resolution_type,'Resolves YES if BTC/USD on Binance spot reaches or exceeds $150,000 at any time on or before 31 Dec 2026 23:59 UTC.',cid,'active',NOW(),'2026-12-31','2027-01-02',0.5,0.5,1200,1200,FALSE,TRUE,NULL,ARRAY['bitcoin','crypto','btc'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-kenya-crypto-law-2026','Will Kenya enact crypto/VASP regulation in 2026?','Kenya has drafted a Virtual Asset Service Providers framework. Will it become law in 2026?','technology'::market_category,'binary'::market_resolution_type,'Resolves YES if Kenya enacts (presidential assent) a virtual-asset/crypto regulation law during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.55,0.45,400,400,FALSE,TRUE,NULL,ARRAY['kenya','crypto','regulation','technology'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-worldcoin-kenya-2026','Will Worldcoin resume operations in Kenya in 2026?','Worldcoin''s Kenya operations were suspended amid data-protection scrutiny. Will it lawfully resume in 2026?','technology'::market_category,'binary'::market_resolution_type,'Resolves YES if Worldcoin/Tools for Humanity resumes public iris-registration operations in Kenya during 2026 with regulatory clearance.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.35,0.65,400,400,FALSE,FALSE,NULL,ARRAY['kenya','worldcoin','technology'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-top-fintech-app-2026','Which will be Kenya''s most-downloaded finance app in 2026?','Kenya''s mobile-money and banking apps compete fiercely for installs.','technology'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the finance app with the most Kenya downloads in 2026 per public app-store/analytics data.',cid,'active',NOW(),'2027-01-31','2027-02-28',0.5,0.5,600,600,FALSE,FALSE,NULL,ARRAY['kenya','fintech','apps','mpesa'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-mpesa-spinoff-2026','Will Safaricom separate M-Pesa into a standalone entity by end 2026?','Safaricom has explored legally separating M-Pesa. Will a standalone M-Pesa entity be established by end-2026?','business'::market_category,'binary'::market_resolution_type,'Resolves YES if Safaricom completes legal separation of M-Pesa into a distinct entity on or before 31 December 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.3,0.7,400,400,FALSE,FALSE,NULL,ARRAY['kenya','mpesa','safaricom'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-starlink-100k-kenya-2026','Will Starlink surpass 100,000 active subscribers in Kenya by end 2026?','Starlink has grown fast in Kenya. Will it exceed 100,000 active subscribers by end-2026?','technology'::market_category,'binary'::market_resolution_type,'Resolves YES if credible reporting/CA data shows Starlink active Kenyan subscribers above 100,000 by 31 December 2026.',cid,'active',NOW(),'2026-12-31','2027-02-15',0.45,0.55,400,400,FALSE,FALSE,NULL,ARRAY['kenya','starlink','internet','technology'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-konza-tenant-2026','Will Konza Technopolis announce a major anchor tenant in 2026?','Konza Technopolis seeks marquee tenants to validate Kenya''s "Silicon Savannah" ambitions.','technology'::market_category,'binary'::market_resolution_type,'Resolves YES if Konza Technopolis officially announces a major new anchor tenant/investor during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,400,400,FALSE,FALSE,NULL,ARRAY['kenya','konza','technology'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-brt-service-2026','Will Nairobi''s BRT begin passenger service in 2026?','Nairobi''s Bus Rapid Transit has faced repeated delays. Will any line begin carrying passengers in 2026?','other'::market_category,'binary'::market_resolution_type,'Resolves YES if any Nairobi BRT line begins scheduled passenger service during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.3,0.7,400,400,FALSE,FALSE,NULL,ARRAY['kenya','nairobi','brt','transport'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-mau-summit-close-2026','Will the Nairobi–Mau Summit highway PPP reach financial close in 2026?','The Rironi–Mau Summit dual-carriageway PPP has been renegotiated repeatedly.','business'::market_category,'binary'::market_resolution_type,'Resolves YES if the Nairobi–Nakuru–Mau Summit highway PPP reaches financial close during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.4,0.6,400,400,FALSE,FALSE,NULL,ARRAY['kenya','infrastructure','roads','ppp'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-sgr-kisumu-2026','Will the SGR extension toward Kisumu/Malaba break ground in 2026?','Kenya has sought funding to extend the Standard Gauge Railway westward.','other'::market_category,'binary'::market_resolution_type,'Resolves YES if construction of an SGR extension beyond Naivasha (toward Kisumu/Malaba) officially breaks ground in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.25,0.75,400,400,FALSE,FALSE,NULL,ARRAY['kenya','sgr','railway','infrastructure'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-jkia-terminal-deal-2026','Will JKIA sign a new terminal/upgrade deal in 2026?','After the cancelled Adani deal, JKIA still needs major upgrades. Will a new deal be signed in 2026?','business'::market_category,'binary'::market_resolution_type,'Resolves YES if a new JKIA terminal construction/upgrade agreement is officially signed during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.45,0.55,400,400,FALSE,FALSE,NULL,ARRAY['kenya','jkia','aviation','infrastructure'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-major-blackout-2026','Will Kenya suffer a nationwide-scale blackout affecting 10+ counties in 2026?','Kenya has experienced several large grid failures. Will another major blackout hit 10+ counties in 2026?','other'::market_category,'binary'::market_resolution_type,'Resolves YES if KPLC/Kenya Power reports a single outage event affecting at least 10 counties during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-10',0.4,0.6,400,400,FALSE,FALSE,NULL,ARRAY['kenya','kplc','power'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-short-rains-above-avg-2026','Will Kenya''s Oct–Dec 2026 short rains be above average?','The Kenya Meteorological Department issues seasonal forecasts for the short rains.','weather'::market_category,'binary'::market_resolution_type,'Resolves YES if KMD''s official assessment rates the Oct–Dec 2026 short rains as above-average nationally.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,400,400,FALSE,FALSE,NULL,ARRAY['kenya','weather','rains','kmd'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-nairobi-floods-under-30-2026','Will the 2026 long-rains flooding kill fewer than 30 people in Kenya?','The 2024 long rains were deadly. This market asks whether 2026 long-rains flood fatalities stay under 30.','weather'::market_category,'binary'::market_resolution_type,'Resolves YES if official government tallies report fewer than 30 flood-related deaths in Kenya during the 2026 long-rains season.',cid,'active',NOW(),'2026-07-31','2026-08-15',0.4,0.6,400,400,FALSE,FALSE,NULL,ARRAY['kenya','weather','floods'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-sha-20m-2026','Will Kenya''s SHA enrol over 20 million people by end 2026?','The Social Health Authority replaced NHIF. Will registered members exceed 20 million by end-2026?','health'::market_category,'binary'::market_resolution_type,'Resolves YES if official SHA figures report more than 20 million registered members by 31 December 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.5,0.5,400,400,FALSE,TRUE,NULL,ARRAY['kenya','sha','health'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-malaria-vaccine-rollout-2026','Will Kenya scale the malaria vaccine to all high-burden counties in 2026?','Kenya piloted the RTS,S malaria vaccine. Will it reach all high-burden counties in 2026?','health'::market_category,'binary'::market_resolution_type,'Resolves YES if the Ministry of Health confirms malaria-vaccine rollout to all designated high-burden counties during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-31',0.55,0.45,400,400,FALSE,FALSE,NULL,ARRAY['kenya','malaria','vaccine','health'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-uni-funding-protest-2026','Will Kenya see nationwide university funding-model protests in 2026?','The new university funding model has sparked student unrest.','social'::market_category,'binary'::market_resolution_type,'Resolves YES if coordinated student protests over the university funding model occur in at least 3 counties during 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.5,0.5,400,400,FALSE,FALSE,NULL,ARRAY['kenya','education','protests','social'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-kenyan-act-global-festival-2026','Will a Kenyan act perform at a major global music festival in 2026?','Kenyan artists are increasingly booked internationally (e.g., Afro Nation, Coachella).','entertainment'::market_category,'binary'::market_resolution_type,'Resolves YES if a Kenyan artist performs at a top-tier international festival (Coachella, Afro Nation, Glastonbury, or similar) in 2026.',cid,'active',NOW(),'2026-12-31','2027-01-15',0.55,0.45,400,400,FALSE,FALSE,NULL,ARRAY['kenya','music','entertainment'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-2027-campaign-issue','Which issue will dominate Kenya''s 2027 campaign?','Campaigns crystallise around a defining theme. Which issue will dominate the 2027 race?','politics'::market_category,'multiple_choice'::market_resolution_type,'Resolves to the issue judged (by major media consensus/polling) to have dominated the 2027 campaign.',cid,'active',NOW(),'2027-08-01','2027-08-20',0.5,0.5,700,700,FALSE,TRUE,NULL,ARRAY['kenya','politics','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI']),
  ('ke-gachagua-dcp-candidate-2027','Will Gachagua''s DCP field a presidential candidate in 2027?','Rigathi Gachagua''s Democratic Congress Party (DCP) is central to opposition plans.','politics'::market_category,'binary'::market_resolution_type,'Resolves YES if the DCP fields (or formally backs as its own) a presidential candidate in the 2027 election.',cid,'active',NOW(),'2027-06-01','2027-06-20',0.6,0.4,400,400,FALSE,FALSE,NULL,ARRAY['kenya','gachagua','dcp','2027'],ARRAY['KE','TZ','UG','RW','ZM','ET','BI'])
  ON CONFLICT (slug) DO NOTHING;
END $$;

-- Multiple-choice options (idempotent per market).
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'William Ruto',0.44,0 FROM public.markets m WHERE slug='ke-2027-president' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Kalonzo Musyoka',0.2,1 FROM public.markets m WHERE slug='ke-2027-president' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Rigathi Gachagua',0.14,2 FROM public.markets m WHERE slug='ke-2027-president' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Fred Matiang''i',0.12,3 FROM public.markets m WHERE slug='ke-2027-president' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Jimi Wanjigi',0.05,4 FROM public.markets m WHERE slug='ke-2027-president' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Another candidate',0.05,5 FROM public.markets m WHERE slug='ke-2027-president' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=5);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Kalonzo Musyoka',0.42,0 FROM public.markets m WHERE slug='ke-opposition-flagbearer-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Rigathi Gachagua',0.24,1 FROM public.markets m WHERE slug='ke-opposition-flagbearer-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Fred Matiang''i',0.16,2 FROM public.markets m WHERE slug='ke-opposition-flagbearer-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Jimi Wanjigi',0.1,3 FROM public.markets m WHERE slug='ke-opposition-flagbearer-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Someone else',0.08,4 FROM public.markets m WHERE slug='ke-opposition-flagbearer-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Kithure Kindiki',0.55,0 FROM public.markets m WHERE slug='ke-ruto-running-mate-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Musalia Mudavadi',0.15,1 FROM public.markets m WHERE slug='ke-ruto-running-mate-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Hassan Joho',0.1,2 FROM public.markets m WHERE slug='ke-ruto-running-mate-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Gladys Wanga',0.08,3 FROM public.markets m WHERE slug='ke-ruto-running-mate-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Anne Waiguru',0.05,4 FROM public.markets m WHERE slug='ke-ruto-running-mate-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Someone else',0.07,5 FROM public.markets m WHERE slug='ke-ruto-running-mate-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=5);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Johnson Sakaja',0.52,0 FROM public.markets m WHERE slug='ke-nairobi-governor-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Polycarp Igathe',0.22,1 FROM public.markets m WHERE slug='ke-nairobi-governor-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Westlands/ODM candidate',0.14,2 FROM public.markets m WHERE slug='ke-nairobi-governor-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Another candidate',0.12,3 FROM public.markets m WHERE slug='ke-nairobi-governor-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Kenya Kwanza',0.48,0 FROM public.markets m WHERE slug='ke-most-assembly-seats-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'United Opposition / Azimio',0.42,1 FROM public.markets m WHERE slug='ke-most-assembly-seats-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Independents / others',0.1,2 FROM public.markets m WHERE slug='ke-most-assembly-seats-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Below 9.00%',0.3,0 FROM public.markets m WHERE slug='ke-cbk-rate-dec2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'9.00%–9.75%',0.4,1 FROM public.markets m WHERE slug='ke-cbk-rate-dec2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'9.75%–10.50%',0.22,2 FROM public.markets m WHERE slug='ke-cbk-rate-dec2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Above 10.50%',0.08,3 FROM public.markets m WHERE slug='ke-cbk-rate-dec2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Technology / Fintech',0.34,0 FROM public.markets m WHERE slug='ke-top-fdi-sector-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Manufacturing',0.2,1 FROM public.markets m WHERE slug='ke-top-fdi-sector-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Energy',0.18,2 FROM public.markets m WHERE slug='ke-top-fdi-sector-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Agriculture',0.16,3 FROM public.markets m WHERE slug='ke-top-fdi-sector-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Real Estate',0.12,4 FROM public.markets m WHERE slug='ke-top-fdi-sector-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Group-stage exit',0.55,0 FROM public.markets m WHERE slug='ke-harambee-run-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Round of 16',0.25,1 FROM public.markets m WHERE slug='ke-harambee-run-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Quarter-final',0.13,2 FROM public.markets m WHERE slug='ke-harambee-run-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Semi-final or better',0.07,3 FROM public.markets m WHERE slug='ke-harambee-run-2027' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Kenya',0.5,0 FROM public.markets m WHERE slug='ke-ea-athletics-top-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Ethiopia',0.38,1 FROM public.markets m WHERE slug='ke-ea-athletics-top-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Uganda',0.1,2 FROM public.markets m WHERE slug='ke-ea-athletics-top-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Another EA nation',0.02,3 FROM public.markets m WHERE slug='ke-ea-athletics-top-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'M-PESA',0.5,0 FROM public.markets m WHERE slug='ke-top-fintech-app-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Equity / Equitel',0.2,1 FROM public.markets m WHERE slug='ke-top-fintech-app-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'KCB',0.14,2 FROM public.markets m WHERE slug='ke-top-fintech-app-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Tala / Branch',0.1,3 FROM public.markets m WHERE slug='ke-top-fintech-app-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Another app',0.06,4 FROM public.markets m WHERE slug='ke-top-fintech-app-2026' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Cost of living / economy',0.4,0 FROM public.markets m WHERE slug='ke-2027-campaign-issue' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=0);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Jobs & youth unemployment',0.24,1 FROM public.markets m WHERE slug='ke-2027-campaign-issue' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=1);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Corruption & governance',0.2,2 FROM public.markets m WHERE slug='ke-2027-campaign-issue' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=2);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Healthcare (SHA)',0.1,3 FROM public.markets m WHERE slug='ke-2027-campaign-issue' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=3);
INSERT INTO public.market_options (market_id,label,price,display_order) SELECT id,'Another issue',0.06,4 FROM public.markets m WHERE slug='ke-2027-campaign-issue' AND NOT EXISTS (SELECT 1 FROM public.market_options o WHERE o.market_id=m.id AND o.display_order=4);
